services:
  db:
    extends: 
      file: compose_prod.yaml
      service: db

  jupyter:
    extends:
      file: compose_prod.yaml
      service: water-quality
    build:
      args:
        BUILD_ENV: "dev"
    ports:
      - ${JUPYTER_PORT}:9988
    volumes:
      - .:/home/jovyan/

  explorer:
    image: opendatacube/explorer:latest
    environment:
    # - DB_HOSTNAME=host.docker.internal
    - POSTGRES_HOSTNAME=db
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASS}
    - POSTGRES_DB=opendatacube
    - POSTGRES_PORT=5432
    - ODC_DEFAULT_INDEX_DRIVER=postgres
    - ODC_POSTGIS_INDEX_DRIVER=postgis
    - ODC_DEFAULT_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@db:5432/opendatacube
    - ODC_POSTGIS_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@db:5432/opendatacube
    - FLASK_ENV=development
    - FLASK_APP=cubedash
    - FLASK_DEBUG=1
    - CUBEDASH_DEFAULT_TIMEZONE=${CUBEDASH_DEFAULT_TIMEZONE}
    # - VIRTUAL_HOST=datacube.explorer
    depends_on:
      - db
    ports:
      - ${EXPLORER_PORT}:8080