services:
  db:
    image: kartoza/postgis:latest
    # volumes:
      # - postgis-data:/var/lib/postgresql
    ports:
        - ${POSTGRES_PORT}:5432
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
        - POSTGRES_MULTIPLE_EXTENSIONS=${POSTGRES_MULTIPLE_EXTENSIONS}
        - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "pg_isready -h 127.0.0.1 -U ${POSTGRES_USER}"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m

  water-quality:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        BUILD_ENV: "prod"
    environment:
      - DB_HOSTNAME=db
      - DB_DATABASE=opendatacube
      - DB_PASSWORD=${POSTGRES_PASS}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PORT=5432
      - GS_NO_SIGN_REQUEST=YES
      - AWS_NO_SIGN_REQUEST=YES
      - AWS_DEFAULT_REGION=af-south-1
    depends_on:
        db:
          condition: service_healthy
    restart: always

volumes:
  postgis-data: